### ISSUE TITLE
Linphone audio headset problem

### ISSUE THREAD

**Issue by julhamptons** [BelledonneCommunications/linphone-android#1106]
Hi,

I use Linphone on my tablet. When I receive a call even if my headset is plugged, the call starts in speaker mode. I think the reason behind this is that Headset Receiver is only enabled when there is an active call. So when my headset is plugged/unplugged before a call, it is not triggered. Do you have a solution for this problem?

Thank you.

**Comment by Viish** [comment]
Hi,
This issue should be fixed in feature/kotlin_rewrite branch.
Cheers,

**Comment by julhamptons** [comment]
But how can I integrate it to my java code?

**Comment by Viish** [comment]
The fix itself is the new AudioDevice API added in linphone-sdk master branch (4.5.0-alpha versions), so you can integrate it in your app (but it's alpha).

**Comment by julhamptons** [comment]
Hi,

I tried with the latest sdk (latest linphone-android-master code) and the problem still continues. The actual problem is, headset receiver is only registered during a call and therefore, if I have my headset connected before a call, the audio is always directed to the speaker.

Thank you.

**Comment by Viish** [comment]
What exactly is the version you use?
With latest SDK, you don't have to use a BluetoothReceiver in the app, everything is handled by the SDK.
So your headset shall be available even before a call occurs. Use the core.getAudioDevices() API to list all available output devices.
Also check you have the following in your build.gradle for the audio focus to be correctly handled:
```
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation "androidx.media:media:1.1.0"
```

**Comment by julhamptons** [comment]
The actual application I use has SDK 4.3+.It has headsetreveicer that is not registered properly. But now I tried with the latest master code downloaded from GIT. Build.gradle does have "implementation 'androidx.appcompat:appcompat:1.1.0'" but does not include "implementation "androidx.media:media:1.1.0" in that code.

Also my headset is wired headset not bluetooth.

**Comment by Viish** [comment]
Nevertheless it won't work unless you use a 4.5+ SDK in your build.gradle.
Also you can checkout the feature/kotlin_rewrite branch that is the most up to date and will become the next master soon.

**Comment by julhamptons** [comment]
Okay, so I will check the feature/kotlin_rewrite branch and wait for the next master code.

Thank you.
