### ISSUE TITLE
Linphone service is always started

### ISSUE THREAD

**Issue by bam80** [BelledonneCommunications/linphone-android#1619]
After latest Linphone Version 4.6.0 update from F-Droid, Linphone service is always started and seen in top panel, even if the app was disabled to start on boot in settings.
If the service forcibly stopped from Apps Info dialog, it starts again for itself since some time.

That behavior is undesirable and regressed since previous versions.

**Comment by Viish** [comment]
Issue has already been fixed in 4.6.1 release, available on Play Store & our website: https://download.linphone.org/releases/android/linphone-android-4.6.1.apk

**Comment by bam80** [comment]
Thanks. I requested update for F-Droid:  
https://gitlab.com/fdroid/fdroiddata/-/issues/2612

**Comment by Viish** [comment]
Don't worry I update them each time we publish a new release so they can update their version as well, it just takes some time.

**Comment by bam80** [comment]
The issue is still there: linphone service starts on boot regardless of the setting, and restarts on timeout being killed.
The only thing that changed is service now stops if the app quits, as earlier, but that only temporary due to above behavior.

**Comment by Viish** [comment]
My bad you are right.

**Comment by Viish** [comment]
Fixed by 07bdc8a0

**Comment by bam80** [comment]
Thanks. Will the new build be out again on F-Droid?

**Comment by Viish** [comment]
I hope so. I'll notify them when we'll have released 4.6.2 version.

**Comment by bam80** [comment]
With the latest update, the issue is still there:
- service exits now along with App quit
- service is still there on boot up

**Comment by Viish** [comment]
Please attach logs, I don't reproduce it on my devices

**Comment by Viish** [comment]
> service exits now along with App quit

That part is expected by the way.

**Comment by bam80** [comment]
Sent to https://www.linphone.org:444//tmp/62273ea793671_a05ae48ce78b68cb5f65.gz

On March 8, 2022 11:05:54 AM GMT+03:00, Sylvain Berfini ***@***.***> wrote:
>Please attach logs, I don't reproduce it on my devices
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/BelledonneCommunications/linphone-android/issues/1619#issuecomment-1061509345
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Viish** [comment]
Seems fine to me (notification will be visible only for 4 seconds):
```
2022-03-08 14:30:46:620 [org.linphone/linphone-android] MESSAGE [Notifications Manager] Starting service as foreground [1]
2022-03-08 14:30:50:006 [org.linphone/linphone-android] MESSAGE [Boot Receiver] Device is starting, autoStart is false
2022-03-08 14:30:50:007 [org.linphone/linphone-android] MESSAGE [Boot Receiver] Auto start setting is disabled, stopping foreground service
2022-03-08 14:30:50:008 [org.linphone/linphone-android] MESSAGE [Notifications Manager] Stopping service as foreground [1]
```

**Comment by bam80** [comment]
The problem is at reappears again later.
I'll send another log when it happens.

**Comment by Viish** [comment]
From your logs your device boots at 14:24:29 and Linphone is started 15:44:02.
However there is no sign of what has started the app. Maybe you did from your app launcher?
Anyway even with "start at boot" disabled, once app is started, if background mode setting is enabled, you will have the service notification visible.

**Comment by linkp** [comment]
I'm not sure why this issue is closed when it still is happening. I am experiencing it on Linphone 4.6.5 from F-Droid on a Samsung Galaxy S22 Ultra running stock Samsung firmware of Android 12 and Samsung One UI 4.1

My Linphone app is set to not start at boot. I do have the notification option enabled to insure that Linphone stays running when I am using it. When I quit the app from the menu, the notification disappears for a while, but it will invariably appear again on its own without me launching it.

I use the app to sign in to the same extension as my office phone which is configured to ring at any time of day, so it is important to me that when I close Linphone, it stays not running.  I had to employ the workaround of disabling the account to prevent it from constantly signing in when the app decides to secretly launch itself in the background. It's quite frustrating.

**Comment by bam80** [comment]
Yep, the issue is very annoying. And it's regression.
So please reopen and investigations are very welcome.

**Comment by Viish** [comment]
I really don't know why this happens. Could you try the following APK please and tell me if issue persists? https://download.linphone.org/snapshots/android/linphone-android-debug-4.6.5.6+e9df5da5e.apk
Thanks in advance.

**Comment by bam80** [comment]
trying it. I added fake account which can't connect. Hopefully it's indifferent for the experiment, but I'll swap it to the real one if needed

**Comment by bam80** [comment]
> I really don't know why this happens. Could you try the following APK please and tell me if issue persists?

@Viish Do not have the problem with this version so far. Do you have an idea what happens?

**Comment by Viish** [comment]
I believe it's the Sync Service that we declare to be able to add information to native contacts that may be started by Android automatically to do the "sync", even though it does nothing.
Keep it for a few days please and if on Monday issue still hasn't came up again, I'll merge the fix and publish a new release.
Thanks for your help.

**Comment by bam80** [comment]
Nice. The question is - why you don't have the issue?

**Comment by Viish** [comment]
May come from differences between your device firmware and mines, battery optimization policies, third party apps, etc...

**Comment by bam80** [comment]
For the reference - I run LineageOS, pretty standard settings/apps

**Comment by bam80** [comment]
> Keep it for a few days please and if on Monday issue still hasn't came up again, I'll merge the fix and publish a new release.

From the two, the only app restarted is the old one. So I think you can apply the fix.

**Comment by bam80** [comment]
> Keep it for a few days please and if on Monday issue still hasn't came up again, I'll merge the fix and publish a new release.

The issue hasn't came up

**Comment by Viish** [comment]
Great! I'll merge it tomorrow and start a new release process, today I'm in vacations ;-)

**Comment by Viish** [comment]
Hi, 4.6.6 release with the fix has been published on the Play Store, F-Droid build is pending. Cheers,

**Comment by Viish** [comment]
Yes it has.
You can use a 4.7.0-alpha version if you want, problem should not appear in it.

**Comment by bam80** [comment]
> You can use a 4.7.0-alpha version if you want,

I can't see it anywhere, is it already out or you are referring to some future version?

**Comment by Viish** [comment]
Yes, 4.7.0 us expected to be published at the end of the month. Until then you can find a nightly build here: https://download.linphone.org/snapshots/android/

**Comment by Viish** [comment]
@bam80 I backported the fix from 4.7.0-alpha to 4.6.7 I released today if you want to update.

**Comment by bam80** [comment]
Thanks, will wait until it hit's f-droid update.
I already tested the nightly and had no problem with it.
