### ISSUE TITLE
How to stay on in background?

### ISSUE THREAD

**Issue by singpolyma** [BelledonneCommunications/linphone-android#55]
I cannot get this app to stay running in background.  Whenever I swipe it closed, the service stops and I get no incoming calls.

Background mode is checked.  I tried unchecking "doze mode" but then the app crashes when I swipe it closed.

Any ideas?

**Comment by DatBewar** [comment]
Hello,
Thanks for reporting the crash with Doze mode it's fixed now:
9754923a8225f33c6f678824fbec5bd4892dde8c
Concerning the background mode, currently this is the push notification which wake up Linphone.

**Comment by singpolyma** [comment]
So, how do I get it to stay on in the background *without* push, since my server doesn't support push notifications?

**Comment by DatBewar** [comment]
Currently you can't stay in the background without push. I don't know if we will change this in the future.

**Comment by pete-gh** [comment]
So I have push enabled, disabled doze mode, but after swiping the app away, I'm still having issues. What can I do?

**Comment by singpolyma** [comment]
@pete-gh push won't actually work with any but their server. We need to add real background support, it seems.

**Comment by keverets** [comment]
CSipSimple stays registered in the background. Has any investigation been done to see how CSipSimple accomplishes it, but linphone does not?

**Comment by pete-gh** [comment]
@singpolyma Indeed it does.
@keverets The only issue I have with CSipSimple, it's ugly and hasn't been updated in 3 years. It does indeed stay in the background though, same as Fongo does, hoping Linphone can do the same one day; both apps stay in the notification bar, even after swiping away the app.

**Comment by JurateT** [comment]
If app was closed, first push notification starts service, but unfortunatelly, no call is received. So second call is needed. I guess call information should be read from push notification.

**Comment by keverets** [comment]
@JurateT my phone does not have google services, so no GCM for push messaging. Linphone should be able to work similarly to CSipSimple & Fongo and stay open in the background (likely with a service) without needing a nudge from a push notification.

**Comment by devurandom** [comment]
I would need background mode to work with sipgate. Can I point them to some document that explains to them how they would need to configure their servers for this to work?

**Comment by bkuhls** [comment]
You could try this: http://lists.nongnu.org/archive/html/linphone-developers/2016-09/msg00014.html

**Comment by v-fox** [comment]
> Currently you can't stay in the background without push. I don't know if we will change this in the future.

Kudos to you for not abandoning F/OSS SIP efforts on Android but this is really irresponsible. I can't persuade 2 of my friends to use Linphone because "this stupid app kills itself". Not to mention that all this "push" crap is just another trojan tactic from Google. We didn't buy >4000mah & 3Gb phones to do something like that. Could you just make a checkbox to disable suicide code from LinphoneService,java ?

Another big turn off is the lack of amplification controls (for some reason, in LP and only LP my BT headset is 5 times quieter than normal) and codec priority. Small one is the lack of auto-recording but that's another matter entirely.

**Comment by zgmunshi** [comment]
There are couple of ways to receive incoming calls if app is killed or screen is locked;
1) The old way,keep the background service enabled so that it will keep on residing in your notification center.
Doing that is really simple as by default it is disabled in latest version of android, you don't need to comment or modify any code,just go to `"res/values/non_localizable_custom.xml"` and find `"kill_service_with_task_manager"` and set its value to `true`. Recompile and build the app, linphone service will be always running.

2) The new as said by Linphone,Push way. What you need to do is just make simple push notification to the device once call is made, the catch you need to make `"data message"` push not `notification message` to make it working.

Regards,
Zeeshan.

**Comment by CodingFanatic** [comment]
Just a minor correction to zgmunshi's comment above.  By setting the "kill_service_with_task_manager" to false (instead of true) and recompiling, the linphone service stays up.

**Comment by herbsmn** [comment]
LinPhone should turn this into a setting option instead of requiring users to recompile the app in order to get it to stay on in the background. There's a lot of Android users that hate Google's proprietary push notifications and it off of their phones. These users should be able to use vanilla LinPhone without having to recompile the app.

**Comment by herbsmn** [comment]
Update: F-Droid is planning on doing the "kill_service_with_task_manager" set to false thing for their version of the build. https://gitlab.com/fdroid/fdroiddata/issues/1029

**Comment by whitetornado** [comment]
any news about this update?

**Comment by juha-h** [comment]
Requiring push in order to stay in the background is a very unfortunate decision.  Please make it configurable in Settings.

**Comment by juha-h** [comment]
It is now impossible on Android O upwards to keep application running and accessing the network when it is not the one that is currently interactive?  Could you czaviar give my Android baresip app https://github.com/juha-h/baresip-studio a try and tell what happened?  It stays registered as long as I don't quit it on my Android 5.1 and 7.1 devices. baresip apk is also available here: https://box.tutpro.com/tmp/baresip.apk.

**Comment by GrahamJB1** [comment]
If you turn on linphone Settings: Advanced: Enable Service Notification, then use the android Notifications linphone app control to not show the banner, as well adding Linphone to Device Maintenance: Battery: Unmonitored Apps to keep the app running you may have better luck on O.
The banner, even if not visible, seems to have a big effect.

**Comment by bharathikrify** [comment]
onMessageReceived not  calling in Firebase service when app is  in background

**Comment by bharathikrify** [comment]
Linphone calls are not working when app in background . 
I am using push notiifcations but the method onMessageReceived() 
is not triggered when my app is in background. 
Any ideas? 
Thanks in advance

**Comment by Viish** [comment]
@bharathikrify Do you have a google-services.json file in your project that match the proxy server your are connecting to ?

**Comment by bharathikrify** [comment]
yes . i have  google-services.json file in my project .

**Comment by Viish** [comment]
Have you updated the project id in res/values/non_localizable_custom.xml in the push_sender_id resource ?

**Comment by zgmunshi** [comment]
> yes. i updated the senderid . i am getting the notifications but onMessageReceived() is not triggered

To trigger onMessageReceived() you need to send "data message" instead of "notification message"
Check this link for details 
https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by bharathikrify** [comment]
I am getting  "data message" even though onMessageReceived method not triggering

**Comment by zgmunshi** [comment]
@bharathikrify To get any further help, kindly share your code with further details like API version you are using & any relevant info.

**Comment by bharathikrify** [comment]
The following method is using to send the  push notification   from server

func AndroidCallNotification(token string, callid string) PushNotification {
    return PushNotification{
        Notifications: []notification{
            notification{
                Tokens:   []string{token},
                Platform: 2,
                Priority: "High",
                Title:    fmt.Sprintf("Incoming call from %s", callid),
                Data: D{
                    "body": fmt.Sprintf("Incoming call from %s", callid),
                },
            },
        },
    }

**Comment by gopipeddisetti** [comment]
I am getting "data message" on onMessageReceived method ,but incoming call not invoked.
Please help me out from this issue.

@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        android.util.Log.i("FirebaseMessaging", "[Push Notification] Received");

        if (!LinphoneService.isReady()) {
            android.util.Log.i("FirebaseMessaging", "[Push Notification] Starting Service");
            Intent intent = new Intent(ACTION_MAIN);
            intent.setClass(this, LinphoneService.class);
            intent.putExtra("PushNotification", true);
            startService(intent);
        } else if (LinphoneManager.isInstanciated() && LinphoneManager.getLc().getCallsNb() == 0) {
            LinphoneUtils.dispatchOnUIThread(new Runnable() {
                @Override
                public void run() {
                    Log.i("[Push Notification] Push notification received with LinphoneManager still alive");
                    if (LinphoneManager.isInstanciated() && LinphoneManager.getLc().getCallsNb() == 0) {
                        LinphoneManager.getLc().setNetworkReachable(false);
                        LinphoneManager.getLc().setNetworkReachable(true);
                    }
                }
            });
        }
    }

03-22 17:26:55.323 24543-25368/org.linphone I/FirebaseMessaging: [Push Notification] Received
03-22 17:26:55.331 24543-24543/org.linphone I/FirebaseMessaging: [Push Notification] Push notification received with LinphoneManager still alive
03-22 17:26:55.331 24543-24543/org.linphone I/FirebaseMessaging: [Push Notification] Push notification received with LinphoneManager isInstanciated

**Comment by Viish** [comment]
So your problem isn't push related.
I can be your client doesn't receive the INVITE from the server (or the server doesn't send the INVITE correctly).

**Comment by gopipeddisetti** [comment]
Hello Viish,
Here is my invite request please correct me if i am did any mistake 

   INVITE sip:666@192.168.75.24:5060 SIP/2.0
   Via: SIP/2.0/UDP 192.168.2.17:56009;branch=z9hG4bK.vjSn0tipX;rport
   From: <sip:50004@192.168.75.24>;tag=t~kW7ghZU
   To: "666" <sip:666@192.168.75.24>
   CSeq: 20 INVITE
   Call-ID: RyYoAOWdho
   Max-Forwards: 70
   Supported: replaces, outbound, gruu
   Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
   Content-Type: application/sdp
   Content-Length: 494
   Contact: <sip:50004@192.168.75.168:36932;app-id=885336110466;pn-type=firebase;pn-tok=ejirqBZAGkQ:APA91bGnpYabdj_-LPaDNK31DN4g4qv-pINllcG5Z-p_d9W3LOY3Hl9AJyiS1XZVXdt-VbAHlSc6gD_8Zzd42cCuXB6fBqE3xj_VVeKbs1viZ50WSsSFbyEKAULU73UkoryFJSz-F46J;pn-silent=1;transport=udp>;expires=300;+sip.instance="<urn:uuid:768ad726-eecd-007c-833f-eff31ec2a637>";+org.linphone.specs=groupchat
   User-Agent: LinphoneAndroid/1.0 (belle-sip/1.6.3)

   v=0
   o=50004 1824 3396 IN IP4 192.168.2.17
   s=Talk
   c=IN IP4 192.168.2.17
   t=0 0
   a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
   m=audio 7076 RTP/AVPF 96 97 98 0 8 18 101 99 100
   a=rtpmap:96 opus/48000/2
   a=fmtp:96 useinbandfec=1
   a=rtpmap:97 speex/16000
   a=fmtp:97 vbr=on
   a=rtpmap:98 speex/8000
   a=fmtp:98 vbr=on
   a=fmtp:18 annexb=yes
   a=rtpmap:101 telephone-event/48000
   a=rtpmap:99 telephone-event/16000
   a=rtpmap:100 telephone-event/8000
   a=rtcp-fb:* ccm tmmbr
   ------------------------------------------------------------------------
send 288 bytes to udp/[192.168.75.168]:36932 at 18:47:22.252736:
   ------------------------------------------------------------------------
   SIP/2.0 100 Trying

**Comment by Viish** [comment]
I think your issue come from the fact you are using UDP which is highly unreliable.
Try TCP or even better TLS and it should work just fine.

**Comment by GrahamJB1** [comment]
Hi,

I can confirm the app being killed has nothing to do with the transport type.
I see the behavior with TCP.
As mentioned you have to override extra settings with new android releases and other apps do this automatically.

Yours ,

Graham
________________________________

**Comment by Viish** [comment]
We're not discussing an app killed issue, but the fact he doesn't receive it's INVITE.
If push is received, app is woken up and a new socket is created to the server. At this time the server is supposed to send the INVITE to the device, but it appears the device doesn't receive it.
This can be caused by the UDP protocol and thus could be fixed by TCP/TLS.

**Comment by brianjmurrell** [comment]
I doubt UDP is as unreliable as you are making it out to be.

**Comment by gopipeddisetti** [comment]
> I think your issue come from the fact you are using UDP which is highly unreliable.
> Try TCP or even better TLS and it should work just fine.

Thanks it's working.

**Comment by gopipeddisetti** [comment]
i am using Oreo when app kills from background  i didn't get the incoming call,how  i will get incoming call when killed.

**Comment by GrahamJB1** [comment]
Please see ‘Hints to keep Linphone alive:’ here:
https://play.google.com/store/apps/details?id=uk.co.systemdevelopment.linphone.taskerplugin

**Comment by Viish** [comment]
You have two ways to stay in "background": either set a foreground notification on the LinphoneService so it won't be killed (service notification in the advanced section of the settings) or use push notifications (which is better) to wake up the app when an call or chat is received.

**Comment by GrahamJB1** [comment]
With Android 8 and 9 these are no longer enough.
As mentioned, there are additional settings that you need to set, otherwise linphone gets suspended (and dies) or gets killed, as part of the much more aggressive power saving features of the OS.

**Comment by Viish** [comment]
@GrahamJB1 I disagree, using push notifications there is absolutely no issues to receive a call or a message at any time.
Furthermore, the doc says that a for Android 9, if the app runs a foreground service it will be categorized in the active bucket: https://developer.android.com/about/versions/pie/power

**Comment by GrahamJB1** [comment]
I found that you were correct prior to Android 8.1 and 9 that the banner was enough.

On those I found linphone stopped responding after a while and clicking on app would attempt to open it but it would immediately close. It would not answer calls at all. Clicking a second time would open it.

I had two rounds of these issues reported by users as new power saving features were added in android 8.1 and 9.

There are two new OS power saving configurations that need updating.

Graham
________________________________

**Comment by GrahamJB1** [comment]
BTW. I was able to easily reproduce the problem on the phones I tested. That is Samsung and Huawei


Graham
________________________________

**Comment by SafeSoft-tlt** [comment]
Works on Android 8.1 (did not check on Android 9):
https://play.google.com/store/apps/details?id=ltd.gmobile
Disable push notifications in the settings. The application intercepts the transition to Doze mode and wakes up the device.

Who will check on Android 9 please report.

**Comment by brianjmurrell** [comment]
> https://play.google.com/store/apps/details?id=ltd.gmobile

Looks remarkably like Linphone.  Where's the source?

https://github.com/BelledonneCommunications/linphone-android/blob/master/LICENSE.txt

**Comment by SafeSoft-tlt** [comment]
> > https://play.google.com/store/apps/details?id=ltd.gmobile
> 
> Looks remarkably like Linphone. Where's the source?
> 
> https://github.com/BelledonneCommunications/linphone-android/blob/master/LICENSE.txt

https://github.com/SafeSoft-tlt/gmobile-android

Almost all the original bugs fixed.

**Comment by GB8994** [comment]
I am also able to integrate it successfully and able to receive a call when the app is in the foreground. But issue occurred when the app is forced closed from Mobile recent tabs, I am not able to receive any call in-app. I have searched for it and also added my google-service.json file as well. and also try by setting the "kill_service_with_task_manager" flag to false in res/values/non_localizable_custom.xml file. But still no luck.

**Comment by arifinjaz** [comment]
Hi Guys,

For people who are non-technical.
Just go to the background setting or battery settings of your phone and make an exception for this app for high power consumption.  
I did it and it is working fine for me.
I'm using Vivo V15.
#WFH
