### ISSUE TITLE
Issue in Samsung S7 for push notification

### ISSUE THREAD

**Issue by bharathikrify** [BelledonneCommunications/linphone-android#743]
Hi 
I am facing an  Issue in Samsung S7 for push notification
While put the phone in deep sleep  i am not receiving the push until i wake up screen. Once i wake up the screen i am getting the push. 
I am using the push for calls. I am getting calls when device in deep sleep once i wakeup the screen only

**Comment by rolloaxel** [comment]
By default, the low-power mode prevents your application from receiving calls because it cuts off access to the network or service in the background.
Manually, you have to go in the settings then Inactive Apps and add your app to the list.
If you are in WiFi mode, make sure, it is in "Always active"...

Programatically, you can't stop the sleep mode from coming, maybe linphone did it with a Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, but it's a restricted option...

**Comment by bharathikrify** [comment]
Thanks for the reply.
But it is working in 3.3.2 code perfectly 
I am facing issue after migrate to 4.1.1

**Comment by bharathikrify** [comment]
I added that permission even though the screen not wakesup until i press any button

**Comment by rolloaxel** [comment]
I'm facing the same problem right now on something different from linphone.

Does the screen light up when the notification is received? I mean, you can see the black screen but the three bottom buttons are displayed.

**Comment by DroidPulkit** [comment]
Is the server sending the notification as high priority?
If your push notifications are high priority then it works even in doze mode

**Comment by bharathikrify** [comment]
yes server is sending the high priority

**Comment by bharathikrify** [comment]
I am getting the calls in deep sleep mode once i press any button

**Comment by DroidPulkit** [comment]
Is there a way to enable deep sleep mode, as soon as you press power button, to test this?

**Comment by Viish** [comment]
When you start Linphone, do you see this log?

> [Platform Helper] Device has been restricted by user (Android 9+), push notifications won't work !

**Comment by bharathikrify** [comment]
Hi viish 
i am manully enableing the notifications for my application

**Comment by Viish** [comment]
> i am manully enableing the notifications for my application

That doesn't answer my question.

**Comment by bharathikrify** [comment]
No Viish i am not seeing the above log 
My receiving the app in DOZE mode 
When i  app receiving the push i am re-registering the account using the refreshregisters method 
This is working fine in 3.3.2 
but in 4.1 my app receiveing the push it is not reregistering the account  even i am using the same refresh registers method 
please help me out here

**Comment by Viish** [comment]
Update the SDK and the app to the latest master version, most probably this is already fixed.

**Comment by bharathikrify** [comment]
Hi Viish 
Thanks for the reply
I am facing the above mentioned issue in doze 
In doze mode the account is  going not connected case in this the refreshregisters( ) method is not working 
I tried manually to registered the account with existing details but it is not working 
I tried the latest code (updated 4 days ago)  in doze mode also  with above scenario 
in that also i am facing the above mentioned issue

**Comment by Viish** [comment]
Hi,
I don't know if you noticed, but in master branch upon receiving a push we no longer use refreshRegister() but instead ensureRegistered() which is smarter.
Are you on master branch also on the SDK ?
If so, can you attach logs if you still have the issue ?

**Comment by bharathikrify** [comment]
Thank you Viish for the response 
I am Using the latest SDK now and ensureRegisterd() method 
But still not getting the calls in DOZE mode 
I observed that network is going to down 
onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@d308fde], proxy = [org.linphone.core.ProxyConfigImpl@d3715bf], state = [None], smessage = [Registration impossible (network down)]
When  device is going to Doze mode 
device  getting the push  
 still getting false for  LinphoneManager.getCore().isNetworkReachable() 
But the socket connection is working in this case in the application 
Help me out to reset the network state 
Or To solve this issue

**Comment by Viish** [comment]
Do you have network monitoring feature enabled ?
In your config file, in the [sip] section:
auto_net_state_mon=1

**Comment by bharathikrify** [comment]
I didn't get you Viish 
Where to set the auto_net_state_mon=1 ?

**Comment by rolloaxel** [comment]
@bharathikrify You have to put this config on your linphonerc file

**Comment by bharathikrify** [comment]
I have that file in my application
Do i need to set auto_net_state_mon=0 or 1 
It is 1 by default

**Comment by bharathikrify** [comment]
I checked with both the 0 and 1 values for auto_net_state_mon  account is not registering when push is coming

**Comment by Viish** [comment]
Have you set the value in the linphonerc_default or linphonerc_factory ?

**Comment by bharathikrify** [comment]
Viish 
linphonerc_factory 
auto_net_state_mon is set to 1 by default 
I checked the deep sleep  
by changing the value to 0 
But account is not registering when i get the push 
it is still in not connected state

**Comment by Viish** [comment]
Can you attach library logs please ?

**Comment by bharathikrify** [comment]
Hello Viish can explain what are library logs ?

**Comment by Viish** [comment]
They are logs outputed by our linphone library (and others).
They are used to debug issues, like yours.

**Comment by bharathikrify** [comment]
Hi viish 

On if used the following
auto_net_state_mon=0
the account is not registered 

onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@65211f5], proxy = [org.linphone.core.ProxyConfigImpl@ae87b8a], state = [None], smessage = [null]


On if used the following
auto_net_state_mon=1

StatusBarFragment: onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@5ec94d4], proxy = [org.linphone.core.ProxyConfigImpl@e60dea6], state = [Ok], smessage = [Registration successful]


When device is going into DOZE mode i am getting the following log

   onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@8d3cb27], proxy = [org.linphone.core.ProxyConfigImpl@464b42f], state = [None], smessage = [Registration impossible (network down)]
            2019-09-09 10:39:38.438 21727-21727/ V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@4a0fa27 nm :  ic=null
2019-09-09 10:39:38.438 21727-21727/ I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2019-09-09 10:39:38.994 21727-21778/ V/FA: Recording user engagement, ms: 23283
            2019-09-09 10:39:39.011 21727-21778/ V/FA: Connecting to remote service
2019-09-09 10:39:39.143 21727-21778/ V/FA: Activity paused, time: 4805216
            2019-09-09 10:39:39.246 21727-21778/ D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=23283, firebase_screen_class(_sc)=ContactsActivity, firebase_screen_id(_si)=6264673194016873192}]
            2019-09-09 10:39:39.292 21727-21733/ I/zygote64: Do partial code cache collection, code=248KB, data=169KB
2019-09-09 10:39:39.292 21727-21733/ I/zygote64: After code cache collection, code=245KB, data=168KB
2019-09-09 10:39:39.292 21727-21733/ I/zygote64: Increasing code cache capacity to 1024KB
2019-09-09 10:39:39.293 21727-21778/ V/FA: Connection attempt already in progress
2019-09-09 10:39:39.294 21727-21778/ D/FA: Connected to remote service
2019-09-09 10:39:39.297 21727-21778/ V/FA: Processing queued up service tasks: 2
            2019-09-09 10:39:40.657 21727-21727/ D/ViewRootImpl@327f2c3[ContactsActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 0 - 0, 144) vi=Rect(0, 0 - 0, 144) or=1
            2019-09-09 10:39:40.926 21727-21727/ D/ViewRootImpl@327f2c3[ContactsActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x3 surface={valid=true 505908068352} changed=false
            2019-09-09 10:39:40.952 21727-21727/ D/ViewRootImpl@327f2c3[ContactsActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 72 - 0, 144) vi=Rect(0, 72 - 0, 144) or=1
            2019-09-09 10:39:40.953 21727-21727/ D/ViewRootImpl@327f2c3[ContactsActivity]: MSG_WINDOW_FOCUS_CHANGED 0
            2019-09-09 10:39:41.044 21727-21727/ D/ViewRootImpl@3d4dd17[LinphoneLauncherActivity]: performDraw() was skipped by AOD_SHOW_STATE... DisplayState=3
            2019-09-09 10:39:41.078 21727-21727/ D/ViewRootImpl@327f2c3[ContactsActivity]: performDraw() was skipped by AOD_SHOW_STATE... DisplayState=3
            2019-09-09 10:39:44.016 21727-21831/ I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
            2019-09-09 10:39:44.018 21727-21831/ I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
            2019-09-09 10:39:44.328 21727-21778/ V/FA: Inactivity, disconnecting from the service

**Comment by bharathikrify** [comment]
if set the values 
register_only_when_network_is_up=0
auto_net_state_mon=0
I am getting the following log 

onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@7db796a], proxy = [org.linphone.core.ProxyConfigImpl@96d2e5b], state = [Ok], smessage = [Registration successful]


In this the account is not gointg not registred condition even when the device is going into doze mode 
but i observed the following behavoiur 
1.The re-registering not happening when click on status bar 
2.I am receiving calls in Doze mode but when i make a call i am getting the error as "Network not reachable"

**Comment by bharathikrify** [comment]
Hi Viish 
Please help me in this issue 
i checked the  following scenarios 



register_only_when_network_is_up | auto_net_state_mon | Registraion State
-- | -- | --
0 | 1 | Registration progress and then failed
1 | 0 | Not registered
0 | 0 | Registration sucess but Re -registration  and out going calls not working
1 | 1 | Registration sucess But in DOZE mode going to not registration state so calls are not working untill we manualy active the  device

**Comment by Viish** [comment]
Keep both values at 1, reproduce the issue and send logs please.

**Comment by bharathikrify** [comment]
@Viish 
Thanks for the replay 
I am getting the logs as below with 
register_only_when_network_is_up=1
auto_net_state_mon=1  values 

when device is in active i am getting the log as 

onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@f34ae54], proxy = [org.linphone.core.ProxyConfigImpl@9fb2781], state = [Ok], smessage = [Registration successful]

----------------------------------------------------------------------------------------------------
when device going into the DOZE mode i am getting the log as below 

StatusBarFragment: onRegistrationStateChanged() called with: core = [org.linphone.core.CoreImpl@f34ae54], proxy = [org.linphone.core.ProxyConfigImpl@9fb2781], state = [None], smessage = [Registration impossible (network down)]

**Comment by Viish** [comment]
Please send full logs from the log upload feature in About fragment.

**Comment by Viish** [comment]
Logs you sent aren't complete.
Please restart linphone app, reproduce issue and send logs again.

**Comment by bharathikrify** [comment]
@Viish 
I am attaching some more logs Please check once 
[5d7904c782936_e079b91387248ffe47ee.gz](https://github.com/BelledonneCommunications/linphone-android/files/3601297/5d7904c782936_e079b91387248ffe47ee.gz)
[5d7905517e9ec_6b469a75b3795ded940e.gz](https://github.com/BelledonneCommunications/linphone-android/files/3601298/5d7905517e9ec_6b469a75b3795ded940e.gz)

**Comment by Viish** [comment]
@bharathikrify why in your logs there is no push notification log ?

**Comment by Viish** [comment]
What version of linphone-android are you using ?

**Comment by bharathikrify** [comment]
@Viish 
We are using the latest master branch SDK 
I will send you the log with the push

**Comment by Viish** [comment]
There are a few things wrong with your logs:

- You connect to sip.linphone.org through UDP which is a very bad idea. Instead use TLS.
- When the push is received, you have a warning message `Refresh register operation not available (network unreachable)` but you shouldn't (even if network reachability is false) because we don't call refreshRegisters (that prints this message) but ensureRegistered (that doesn't).
- `[Platform Helper] Is app in device battery optimization whitelist: false` means that you will have issues with push notifications indeed.

**Comment by bharathikrify** [comment]
@Viish 
We are using the TCP now
We also removed the refresh registers code 
Please check once again 

[5d7b9aebdd414_e049128b83e28fc257cd.gz](https://github.com/BelledonneCommunications/linphone-android/files/3610260/5d7b9aebdd414_e049128b83e28fc257cd.gz)

**Comment by Viish** [comment]
Your app isn't whitelisted by the phone by battery optimizer, it won't work.
