### ISSUE TITLE
how to transfer call?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#876]
It's not at all intuitive how I transfer a call I am currently on to another extension.

I get as far as having the first call on hold and being on a call with the party I am trying to transfer to but nothing I try at that point successfully transfers the call.

Could this be documented somewhere with either a video or some screenshots?

**Comment by Viish** [comment]
Simply click on transfer button while on a call, choose the person you want to transfer the call to (either a contact, a history entry or type it from the dialer) and click the transfer button on the dialer.

**Comment by brianjmurrell** [comment]
I believe I know which one the transfer button is, but let's get perfectly clear about it.  Can you paste a screenshot here?  I wouldn't be so pedantic about it except that what you describe is just not working for me, so I can only assume I must be pressing the wrong button.

**Comment by brianjmurrell** [comment]
Is this:

![image](https://user-images.githubusercontent.com/559317/70914574-42178c00-1fe6-11ea-9a38-185018bbd81f.png)

the transfer button?  If so, it doesn't work.  

On the next screen:

![image](https://user-images.githubusercontent.com/559317/70915011-1943c680-1fe7-11ea-96e8-763778185eab.png)

I type in the extension I want to transfer to and click the red circled button and then just end up with two calls (the one that I want to transfer and a call to the destination I want to transfer to) in progress that I can switch back and forth to but I cannot actually complete the transfer and get out of the call:

![image](https://user-images.githubusercontent.com/559317/70915266-90795a80-1fe7-11ea-91cc-6b04cd72257b.png)

So what am I supposed to do at that point to get out of the middle of the two parties and connect them together, completing the transfer?

**Comment by Viish** [comment]
> Is this: the transfer button? If so, it doesn't work.

Yes it is. Indeed from your screens it doesn't work, I fixed this already a few weeks back, you should update to our latest published released (4.2)

**Comment by brianjmurrell** [comment]
Is that fix on master?  I'm currently on 4.3-alpha.4+e82436e18 with SDK 4.3.0-beta.42+3c49a08.

**Comment by Viish** [comment]
Yes, release/4.2 branch was merged on master after the release.

**Comment by brianjmurrell** [comment]
So then supposedly I have the fix in my build I think is what you are saying.  Except I am still experiencing it.  Should this ticket be reopened then?

**Comment by brianjmurrell** [comment]
Is my supposition correct here?  Is my release supposed to contain the fix you said went into 4.2 for this?  Should we reopen this ticket?

**Comment by Viish** [comment]
Indeed it was broken.
Fixed in branches release/4.2 and master.

**Comment by brianjmurrell** [comment]
Hrm.  My build from 777359e29 is suffering from:

```
12-17 12:40:11.281 21361 21361 E AndroidRuntime: FATAL EXCEPTION: main
12-17 12:40:11.281 21361 21361 E AndroidRuntime: Process: org.linphone.debug, PID: 21361
12-17 12:40:11.281 21361 21361 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone.debug-DhIhkzp7t3MLI6K0MRUyxQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone.debug-DhIhkzp7t3MLI6K0MRUyxQ==/lib/arm64, /data/app/org.linphone.debug-DhIhkzp7t3MLI6K0MRUyxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libc++_shared.so"
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1660)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at org.linphone.core.FactoryImpl.<clinit>(Factory.java:295)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at org.linphone.core.Factory.instance(Factory.java:44)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at org.linphone.LinphoneContext.<init>(LinphoneContext.java:101)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at org.linphone.service.LinphoneService.onCreate(LinphoneService.java:56)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3961)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2092)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7523)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
12-17 12:40:11.281 21361 21361 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
12-17 12:40:11.284  1093  1693 W ActivityManager:   Force finishing activity org.linphone.debug/org.linphone.activities.LinphoneLauncherActivity
```

I've even `rm -rf ~/.gradle/caches/` and rebuilt and the same thing.

I do recall having run into this once before but searching for what solved it didn't yield anything unfortunately.

**Comment by Viish** [comment]
In Android studio do a project clean and rebuild

**Comment by brianjmurrell** [comment]
For anyone (including myself :-)) who comes to find the solution to the [above mentioned problem](https://github.com/BelledonneCommunications/linphone-android/issues/876#issuecomment-566671424):

```bash
./gradlew clean
```

**Comment by brianjmurrell** [comment]
Is it possible to not have the tones being made when entering the extension to transfer to not be sent to the party being transferred?  It's annoying for a human at the other end to have to listen to and can mess up IVRs if transferring while on an IVR.
